# Generated by Django 5.2.6 on 2025-10-04 19:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Strength', 'Strength Training'), ('Cardio', 'Cardiovascular'), ('Flexibility', 'Flexibility & Mobility'), ('Sport', 'Sports'), ('Recovery', 'Recovery & Rehabilitation')], help_text='The category of activity this achievement applies to.', max_length=20)),
                ('metric', models.CharField(choices=[('volume', 'Total Volume (kg)'), ('duration', 'Total Duration (minutes)'), ('frequency', 'Workout Frequency (count)')], help_text='The metric to track for this achievement.', max_length=20)),
                ('target_value', models.FloatField(help_text='The target value the user must reach.')),
                ('points_reward', models.PositiveIntegerField(help_text='Points awarded upon completion.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['category', 'target_value'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#FFFFFF', help_text='Hex color code for the category, e.g., #4A90E2', max_length=7)),
            ],
            options={
                'verbose_name': 'Competition Category',
                'verbose_name_plural': 'Competition Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Strength', 'Strength Training'), ('Cardio', 'Cardiovascular'), ('Flexibility', 'Flexibility & Mobility'), ('Sport', 'Sports'), ('Recovery', 'Recovery & Rehabilitation')], max_length=20)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('description', models.TextField()),
                ('target_muscles', models.TextField()),
                ('calories_per_hour', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)])),
                ('difficulty_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('equipment_needed', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fitness Activity',
                'verbose_name_plural': 'Fitness Activities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], max_length=10)),
                ('calories_per_100g', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('protein_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('carbs_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fat_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fiber_per_100g', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('serving_size', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('affected_part', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('first_aid', models.TextField()),
                ('treatment_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('recovery_time_days', models.PositiveIntegerField(blank=True, help_text='Estimated recovery time in days', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Injury',
                'verbose_name_plural': 'Injuries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('Strength', 'Strength Training'), ('Cardio', 'Cardiovascular'), ('Flexibility', 'Flexibility & Mobility'), ('Sport', 'Sports'), ('Recovery', 'Recovery & Rehabilitation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#4A90E2', help_text='Hex color for this category', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Training Category',
                'verbose_name_plural': 'Training Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_types', to='api.competitioncategory')),
            ],
            options={
                'verbose_name': 'Competition Type',
                'verbose_name_plural': 'Competition Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True, validators=[django.core.validators.MaxValueValidator(1440)])),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('fitness_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.fitnessactivity')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic Blood Pressure (upper value)', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic Blood Pressure (lower value)', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='Blood Oxygen Saturation (%)', null=True)),
                ('stress_level', models.PositiveIntegerField(blank=True, help_text='A score representing stress, e.g., 1-100', null=True)),
                ('steps_today', models.PositiveIntegerField(blank=True, help_text='Cumulative steps for the day of the reading', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Data Log',
                'verbose_name_plural': 'Health Data Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlanPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='A summary of the goals for this phase.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order of the phase (e.g., 1 for Day Before, 2 for Competition Day).')),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_phases', to='api.competitiontype')),
            ],
            options={
                'verbose_name': 'Plan Phase',
                'verbose_name_plural': 'Plan Phases',
                'ordering': ['competition_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Nutrition', 'Nutrition'), ('Hydration', 'Hydration'), ('Workout', 'Workout / Exercise'), ('Recovery', 'Recovery / Rest'), ('Mindset', 'Mindset / Mental Prep'), ('Warning', 'What to Avoid')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='The detailed advice or instruction.')),
                ('amount_suggestion', models.CharField(blank=True, help_text="Optional: Suggested amounts, e.g., '3 liters' or '20g protein'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order of this item within the phase.')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='api.planphase')),
            ],
            options={
                'verbose_name': 'Plan Item',
                'verbose_name_plural': 'Plan Items',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(500.0)])),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(250.0)])),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance')], default='muscle_gain', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little/no exercise)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('extra_active', 'Extra Active (very hard exercise/sports & physical job)')], default='moderately_active', max_length=20)),
                ('diet_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=10)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_points', models.PositiveIntegerField(default=0, help_text='Total points earned from achievements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('reps', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1440)])),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3600)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.activity')),
            ],
            options={
                'verbose_name': 'Set Log',
                'verbose_name_plural': 'Set Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True, validators=[django.core.validators.MaxValueValidator(480)])),
                ('difficulty_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('color_code', models.CharField(default='#7ED321', help_text='Hex color for this workout', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.trainingcategory')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['training_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_muscles', models.CharField(max_length=200)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('sets_recommended', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reps_recommended', models.CharField(blank=True, help_text="e.g., '8-12', '30 seconds', 'to failure'", max_length=50)),
                ('rest_between_sets', models.PositiveIntegerField(blank=True, help_text='Rest time in seconds', null=True, validators=[django.core.validators.MaxValueValidator(600)])),
                ('instructions', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workout')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['workout', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.FloatField(default=0, help_text="The user's current progress towards the target.")),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
