# Generated by Django 5.2.6 on 2025-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='imageUrl',
            field=models.CharField(blank=True, help_text='URL for the workout image', max_length=255, null=True),
        ),
    ]
